org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=26.1-snapshot-4
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=26.1.0.0-alpha.8+snapshot-4

## Mod Properties
mod_id=tmcore
mod_name=TechnoMatrixCore
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=net.nilarea
mod_authors=NilArea
mod_description=